export const cryptoSymbols = [
    { "id": 1, "name": "Bitcoin", "symbol": "BTC" },
    { "id": 2, "name": "Ethereum", "symbol": "ETH" },
    { "id": 3, "name": "Ripple", "symbol": "XRP" },
    { "id": 4, "name": "Litecoin", "symbol": "LTC" },
    { "id": 5, "name": "Cardano", "symbol": "ADA" },
    { "id": 6, "name": "Polkadot", "symbol": "DOT" },
    { "id": 7, "name": "Bitcoin Cash", "symbol": "BCH" },
    { "id": 8, "name": "Chainlink", "symbol": "LINK" },
    { "id": 9, "name": "Stellar", "symbol": "XLM" },
    { "id": 10, "name": "USD Coin", "symbol": "USDC" },
    { "id": 11, "name": "Binance Coin", "symbol": "BNB" },
    { "id": 12, "name": "Tether", "symbol": "USDT" },
    { "id": 13, "name": "Dogecoin", "symbol": "DOGE" },
    { "id": 14, "name": "Wrapped Bitcoin", "symbol": "WBTC" },
    { "id": 15, "name": "Bitcoin SV", "symbol": "BSV" },
    { "id": 16, "name": "Aave", "symbol": "AAVE" },
    { "id": 17, "name": "Cosmos", "symbol": "ATOM" },
    { "id": 18, "name": "Monero", "symbol": "XMR" },
    { "id": 19, "name": "TRON", "symbol": "TRX" },
    { "id": 20, "name": "EOS", "symbol": "EOS" },
    { "id": 21, "name": "Neo", "symbol": "NEO" },
    { "id": 22, "name": "Solana", "symbol": "SOL" },
    { "id": 23, "name": "THETA", "symbol": "THETA" },
    { "id": 24, "name": "VeChain", "symbol": "VET" },
    { "id": 25, "name": "Filecoin", "symbol": "FIL" },
    { "id": 26, "name": "Crypto.com Coin", "symbol": "CRO" },
    { "id": 27, "name": "Huobi Token", "symbol": "HT" },
    { "id": 28, "name": "IOTA", "symbol": "MIOTA" },
    { "id": 29, "name": "Tezos", "symbol": "XTZ" },
    { "id": 30, "name": "Theta Fuel", "symbol": "TFUEL" },
    { "id": 31, "name": "Dai", "symbol": "DAI" },
    { "id": 32, "name": "Celsius Network", "symbol": "CEL" },
    { "id": 33, "name": "Compound", "symbol": "COMP" },
    { "id": 34, "name": "Maker", "symbol": "MKR" },
    { "id": 35, "name": "UNUS SED LEO", "symbol": "LEO" },
    { "id": 36, "name": "Dash", "symbol": "DASH" },
    { "id": 37, "name": "Kusama", "symbol": "KSM" },
    { "id": 38, "name": "Zcash", "symbol": "ZEC" },
    { "id": 39, "name": "Compound Dai", "symbol": "CDAI" },
    { "id": 40, "name": "BitTorrent", "symbol": "BTT" },
    { "id": 41, "name": "SushiSwap", "symbol": "SUSHI" },
    { "id": 42, "name": "PancakeSwap", "symbol": "CAKE" },
    { "id": 43, "name": "Synthetix", "symbol": "SNX" },
    { "id": 44, "name": "yearn.finance", "symbol": "YFI" },
    { "id": 45, "name": "Chiliz", "symbol": "CHZ" },
    { "id": 46, "name": "Decred", "symbol": "DCR" },
    { "id": 47, "name": "Hedera Hashgraph", "symbol": "HBAR" },
    { "id": 48, "name": "Zilliqa", "symbol": "ZIL" },
    { "id": 49, "name": "Quant", "symbol": "QNT" },
    { "id": 50, "name": "FTX Token", "symbol": "FTT" },
    { "id": 51, "name": "Ontology", "symbol": "ONT" },
    { "id": 52, "name": "ICON", "symbol": "ICX" },
    { "id": 53, "name": "Avalanche", "symbol": "AVAX" },
    { "id": 54, "name": "Basic Attention Token", "symbol": "BAT" },
    { "id": 55, "name": "Holo", "symbol": "HOT" },
    { "id": 56, "name": "Ren", "symbol": "REN" },
    { "id": 57, "name": "OKB", "symbol": "OKB" },
    { "id": 58, "name": "The Graph", "symbol": "GRT" },
    { "id": 59, "name": "Siacoin", "symbol": "SC" },
    { "id": 60, "name": "Waves", "symbol": "WAVES" }
]

export const getCryptoName =(symbol:string) =>{
    const crypto =  cryptoSymbols.find(crypto => crypto.symbol === symbol);
    return crypto? crypto.name : '';

}

export const cryptoItems = [
{ id: 1, name: "Bitcoin", symbol: "BTC", price: null },
{ id: 2, name: "Ethereum", symbol: "ETH", price: null },
{ id: 3, name: "Ripple", symbol: "XRP", price: null },
{ id: 4, name: "Litecoin", symbol: "LTC", price: null },
{ id: 5, name: "Cardano", symbol: "ADA", price: null },
{ id: 6, name: "Polkadot", symbol: "DOT", price: null },
{ id: 7, name: "Bitcoin Cash", symbol: "BCH", price: null },
{ id: 8, name: "Chainlink", symbol: "LINK", price: null },
{ id: 9, name: "Stellar", symbol: "XLM", price: null },
{ id: 10, name: "USD Coin", symbol: "USDC", price: null },
{ id: 11, name: "Binance Coin", symbol: "BNB", price: null },
{ id: 12, name: "Tether", symbol: "USDT", price: null },
{ id: 13, name: "Dogecoin", symbol: "DOGE", price: null },
{ id: 14, name: "Wrapped Bitcoin", symbol: "WBTC", price: null },
{ id: 15, name: "Bitcoin SV", symbol: "BSV", price: null },
{ id: 16, name: "Aave", symbol: "AAVE", price: null },
{ id: 17, name: "Cosmos", symbol: "ATOM", price: null },
{ id: 18, name: "Monero", symbol: "XMR", price: null },
{ id: 19, name: "TRON", symbol: "TRX", price: null },
{ id: 20, name: "EOS", symbol: "EOS", price: null },
{ id: 21, name: "Neo", symbol: "NEO", price: null },
{ id: 22, name: "Solana", symbol: "SOL", price: null },
{ id: 23, name: "THETA", symbol: "THETA", price: null },
{ id: 24, name: "VeChain", symbol: "VET", price: null },
{ id: 25, name: "Filecoin", symbol: "FIL", price: null },
{ id: 26, name: "Crypto.com Coin", symbol: "CRO", price: null },
{ id: 27, name: "Huobi Token", symbol: "HT", price: null },
{ id: 28, name: "IOTA", symbol: "MIOTA", price: null },
{ id: 29, name: "Tezos", symbol: "XTZ", price: null },
{ id: 30, name: "Theta Fuel", symbol: "TFUEL", price: null },
{ id: 31, name: "Dai", symbol: "DAI", price: null },
{ id: 32, name: "Celsius Network", symbol: "CEL", price: null },
{ id: 33, name: "Compound", symbol: "COMP", price: null },
{ id: 34, name: "Maker", symbol: "MKR", price: null },
{ id: 35, name: "UNUS SED LEO", symbol: "LEO", price: null },
{ id: 36, name: "Dash", symbol: "DASH", price: null },
{ id: 37, name: "Kusama", symbol: "KSM", price: null },
{ id: 38, name: "Zcash", symbol: "ZEC", price: null },
{ id: 39, name: "Compound Dai", symbol: "CDAI", price: null },
{ id: 40, name: "BitTorrent", symbol: "BTT", price: null },
{ id: 41, name: "SushiSwap", symbol: "SUSHI", price: null },
{ id: 42, name: "PancakeSwap", symbol: "CAKE", price: null },
{ id: 43, name: "Synthetix", symbol: "SNX", price: null },
{ id: 44, name: "yearn.finance", symbol: "YFI", price: null },
{ id: 45, name: "Chiliz", symbol: "CHZ", price: null },
{ id: 46, name: "Decred", symbol: "DCR", price: null },
{ id: 47, name: "Hedera Hashgraph", symbol: "HBAR", price: null },
{ id: 48, name: "Zilliqa", symbol: "ZIL", price: null },
{ id: 49, name: "Quant", symbol: "QNT", price: null },
{ id: 50, name: "FTX Token", symbol: "FTT", price: null },
{ id: 51, name: "Ontology", symbol: "ONT", price: null },
{ id: 52, name: "ICON", symbol: "ICX", price: null },
{ id: 53, name: "Avalanche", symbol: "AVAX", price: null },
{ id: 54, name: "Basic Attention Token", symbol: "BAT", price: null },
{ id: 55, name: "Holo", symbol: "HOT", price: null },
{ id: 56, name: "Ren", symbol: "REN", price: null },
{ id: 57, name: "OKB", symbol: "OKB", price: null },
{ id: 58, name: "The Graph", symbol: "GRT", price: null },
{ id: 59, name: "Siacoin", symbol: "SC", price: null },
{ id: 60, name: "Waves", symbol: "WAVES", price: null }

];