const cryptoSymbols = [
    { "id": 1, "name": "Bitcoin", "symbol": "BTC" },
    { "id": 2, "name": "Ethereum", "symbol": "ETH" },
    { "id": 3, "name": "Ripple", "symbol": "XRP" },
    { "id": 4, "name": "Litecoin", "symbol": "LTC" },
    { "id": 5, "name": "Cardano", "symbol": "ADA" },
    { "id": 6, "name": "Polkadot", "symbol": "DOT" },
    { "id": 7, "name": "Bitcoin Cash", "symbol": "BCH" },
    { "id": 8, "name": "Chainlink", "symbol": "LINK" },
    { "id": 9, "name": "Stellar", "symbol": "XLM" },
    { "id": 10, "name": "USD Coin", "symbol": "USDC" },
    { "id": 11, "name": "Binance Coin", "symbol": "BNB" },
    { "id": 12, "name": "Tether", "symbol": "USDT" },
    { "id": 13, "name": "Dogecoin", "symbol": "DOGE" },
    { "id": 14, "name": "Wrapped Bitcoin", "symbol": "WBTC" },
    { "id": 15, "name": "Bitcoin SV", "symbol": "BSV" },
    { "id": 16, "name": "Aave", "symbol": "AAVE" },
    { "id": 17, "name": "Cosmos", "symbol": "ATOM" },
    { "id": 18, "name": "Monero", "symbol": "XMR" },
    { "id": 19, "name": "TRON", "symbol": "TRX" },
    { "id": 20, "name": "EOS", "symbol": "EOS" },
    { "id": 21, "name": "Neo", "symbol": "NEO" },
    { "id": 22, "name": "Solana", "symbol": "SOL" },
    { "id": 23, "name": "THETA", "symbol": "THETA" },
    { "id": 24, "name": "VeChain", "symbol": "VET" },
    { "id": 25, "name": "Filecoin", "symbol": "FIL" },
    { "id": 26, "name": "Crypto.com Coin", "symbol": "CRO" },
    { "id": 27, "name": "Huobi Token", "symbol": "HT" },
    { "id": 28, "name": "IOTA", "symbol": "MIOTA" },
    { "id": 29, "name": "Tezos", "symbol": "XTZ" },
    { "id": 30, "name": "Theta Fuel", "symbol": "TFUEL" },
    { "id": 31, "name": "Dai", "symbol": "DAI" },
    { "id": 32, "name": "Celsius Network", "symbol": "CEL" },
    { "id": 33, "name": "Compound", "symbol": "COMP" },
    { "id": 34, "name": "Maker", "symbol": "MKR" },
    { "id": 35, "name": "UNUS SED LEO", "symbol": "LEO" },
    { "id": 36, "name": "Dash", "symbol": "DASH" },
    { "id": 37, "name": "Kusama", "symbol": "KSM" },
    { "id": 38, "name": "Zcash", "symbol": "ZEC" },
    { "id": 39, "name": "Compound Dai", "symbol": "CDAI" },
    { "id": 40, "name": "BitTorrent", "symbol": "BTT" },
    { "id": 41, "name": "SushiSwap", "symbol": "SUSHI" },
    { "id": 42, "name": "PancakeSwap", "symbol": "CAKE" },
    { "id": 43, "name": "Synthetix", "symbol": "SNX" },
    { "id": 44, "name": "yearn.finance", "symbol": "YFI" },
    { "id": 45, "name": "Chiliz", "symbol": "CHZ" },
    { "id": 46, "name": "Decred", "symbol": "DCR" },
    { "id": 47, "name": "Hedera Hashgraph", "symbol": "HBAR" },
    { "id": 48, "name": "Zilliqa", "symbol": "ZIL" },
    { "id": 49, "name": "Quant", "symbol": "QNT" },
    { "id": 50, "name": "FTX Token", "symbol": "FTT" },
    { "id": 51, "name": "Ontology", "symbol": "ONT" },
    { "id": 52, "name": "ICON", "symbol": "ICX" },
    { "id": 53, "name": "Avalanche", "symbol": "AVAX" },
    { "id": 54, "name": "Basic Attention Token", "symbol": "BAT" },
    { "id": 55, "name": "Holo", "symbol": "HOT" },
    { "id": 56, "name": "Ren", "symbol": "REN" },
    { "id": 57, "name": "OKB", "symbol": "OKB" },
    { "id": 58, "name": "The Graph", "symbol": "GRT" },
    { "id": 59, "name": "Siacoin", "symbol": "SC" },
    { "id": 60, "name": "Waves", "symbol": "WAVES" }
]

export const getCryptoName =(symbol:string) =>{
    const crypto =  cryptoSymbols.find(crypto => crypto.symbol === symbol);
    return crypto? crypto.name : '';

}